<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Media;
use Illuminate\Support\Collection;
use Vendor\Webtrees\Module\MediaBadge\MediaBadgeModule;

/**
 * @var Collection<int,Media> $media_list
 */

?>

<div class="wt-tab-album">
    <div style="background:#fff3cd;color:#664d03;padding:0.5rem;margin-bottom:1rem;">
    Media Badge Album Override aktiv
</div>
    <?php foreach ($media_list as $media) : ?>
        <figure class="figure text-center col-sm-6 col-md-4 col-lg-3 col-xl-2 wt-album-tab-figure">
            <?php foreach ($media->mediaFiles() as $media_file) : ?>
                <?= $media_file->displayImage(100, 100, 'contain', ['class' => 'img-thumbnail wt-album-tab-image']) ?>
            <?php endforeach ?>

            <figcaption class="figure-caption wt-album-tab-caption">
                <span class="mbg-media-title-line mbg-media-title-line--center">
                    <?= view(MediaBadgeModule::MODULE_NAME . '::components/media-badge-list', [
                        'record'   => $media,
                        'position' => 'before-title',
                    ]) ?>

                    <a href="<?= e($media->url()) ?>">
                        <?= $media->fullName() ?>
                    </a>

                    <?= view(MediaBadgeModule::MODULE_NAME . '::components/media-badge-list', [
                        'record'   => $media,
                        'position' => 'after-title',
                    ]) ?>
                </span>
            </figcaption>
        </figure>
    <?php endforeach ?>
</div>
