<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Illuminate\Support\Collection;
use Vendor\Webtrees\Module\MediaBadge\MediaBadgeModule;

/**
 * @var bool                 $can_edit
 * @var Collection<int,Fact> $clipboard_facts
 * @var Collection<int,Fact> $facts
 * @var Individual           $individual
 */

?>
<div class="wt-tab-media">
    <table class="table wt-facts-table">
        <tr>
            <td colspan="2">
                <label>
                    <input id="show-level-2-media" type="checkbox" data-bs-toggle="collapse" data-bs-target=".wt-level-two-media" data-wt-persist="level-two-media" autocomplete="off">
                    <?= I18N::translate('Show all media') ?>
                </label>
            </td>
        </tr>

        <?php foreach ($facts as $fact) : ?>
            <?php if (str_ends_with($fact->tag(), ':OBJE') && $fact->target() instanceof Media) : ?>
                <?php
                $media = $fact->target();

                if ($fact->isPendingAddition()) {
                    $styleadd = 'wt-new ';
                } elseif ($fact->isPendingDeletion()) {
                    $styleadd = 'wt-old ';
                } else {
                    $styleadd = '';
                }
                ?>

                <tr class="<?= trim($styleadd) ?>">
                    <th scope="row" class="rela <?= $styleadd ?>">
                        <?= $fact->label() ?>
                        <?= view('fact-edit-links', ['fact' => $fact, 'url' => $fact->record()->url() . '#tab-media']) ?>
                    </th>

                    <td class="<?= $styleadd ?>">
                        <div class="d-flex flex-wrap mb-2">
                            <?php foreach ($media->mediaFiles() as $media_file) : ?>
                                <div class="me-1 mb-1">
                                    <?= $media_file->displayImage(100, 100, 'contain', []) ?>
                                </div>
                            <?php endforeach ?>
                        </div>

                        <div class="mbg-media-title-line mb-2">
                            <?= view(MediaBadgeModule::MODULE_NAME . '::components/media-badge-list', [
                                'record'   => $media,
                                'position' => 'before-title',
                            ]) ?>

                            <a href="<?= e($media->url()) ?>">
                                <?= $media->fullName() ?>
                            </a>

                            <?= view(MediaBadgeModule::MODULE_NAME . '::components/media-badge-list', [
                                'record'   => $media,
                                'position' => 'after-title',
                            ]) ?>
                        </div>

                        <?php foreach ($media->facts(['NOTE']) as $note) : ?>
                            <?= view('fact-gedcom-fields', [
                                'gedcom' => $note->gedcom(),
                                'parent' => $media->tag(),
                                'tree'   => $fact->record()->tree(),
                            ]) ?>
                        <?php endforeach ?>
                    </td>
                </tr>

            <?php elseif (str_ends_with($fact->tag(), ':OBJE')) : ?>
                <?= view('fact', ['fact' => $fact, 'record' => $individual]) ?>

            <?php else : ?>
                <?php
                if ($fact->isPendingAddition()) {
                    $styleadd = 'wt-new ';
                } elseif ($fact->isPendingDeletion()) {
                    $styleadd = 'wt-old ';
                } else {
                    $styleadd = '';
                }
                ?>

                <tr class="wt-level-two-media collapse">
                    <th scope="row" class="rela <?= $styleadd ?>">
                        <?= $fact->label() ?>
                        <?= view('fact-edit-links', ['fact' => $fact, 'url' => $fact->record()->url() . '#tab-media']) ?>
                    </th>

                    <td class="<?= $styleadd ?>">
                        <?php if (preg_match_all('/\n([2-4] OBJE .*)/', $fact->gedcom(), $matches, PREG_SET_ORDER) > 0) : ?>
                            <?php foreach ($matches as $match) : ?>
                                <?= view('fact-gedcom-fields', [
                                    'gedcom' => $match[1],
                                    'parent' => $fact->tag(),
                                    'tree'   => $fact->record()->tree(),
                                ]) ?>
                            <?php endforeach ?>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>

        <?php if ($facts->isEmpty()) : ?>
            <tr>
                <td colspan="2">
                    <?= I18N::translate('There are no media objects for this individual.') ?>
                </td>
            </tr>
        <?php endif ?>
    </table>
</div>
